import Head from "next/head";
import { AiFillMediumCircle, AiFillLinkedin, AiFillGithub,} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import Button from "react-bootstrap/Button";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import bocacode from "../public/bocacode.png";
import pitchvote from "../public/pitchvote.png";
import reactmovies from "../public/reactmovies.png";
import united from "../public/united.png";
// import web5 from "../public/web5.png";
// import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Edgar&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">my portfolio</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <Button
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://docs.google.com/document/d/e/2PACX-1vRznf0G-VtnipDy4CpLnXmjXgNBDuE9DrHpZx-jp_Z0KLK-NS4Oz8ClC88IJrYjqMALq5WDKXforwpb/pub"
                >
                  Resume
                </Button>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Edgar Davila
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Full-Stack Developer and Engineer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              I offer my expertise in programming and design to help with any of
              your content needs. Please contact me to begin working on your
              project!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <Button href="https://medium.com/@davila.fullrecord.edgar">
                <AiFillMediumCircle />
              </Button>
              <Button href="https://www.linkedin.com/in/edgar-david/">
                <AiFillLinkedin />
              </Button>
              <Button href="https://github.com/beboopr">
                <AiFillGithub />
              </Button>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image 
              src={deved} 
              // layout="fill" 
              // objectFit="cover"
              alt="image of an avatar"/>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              As a freelance designer and developer, I have a diverse experience
              working remotely for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborating with a talented team to produce digital products
              for both business and consumer use throughout my career journey.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including web app design,
              programming, Full CRUD App.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} alt="icon logo"/>
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Antdesign</p>
              <p className="text-gray-800 py-1">Material UI</p>
              <p className="text-gray-800 py-1">BootStrap</p>
              <p className="text-gray-800 py-1">Taillwindcss</p>
              <p className="text-gray-800 py-1">And More...</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} alt="hashtag icon"/>
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Let&apos;s make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-600">Dev Tools I Use</h4>
              <p className="text-gray-800 py-1">MERN Stack</p>
              <p className="text-gray-800 py-1">FERN Stack</p>
              <p className="text-gray-800 py-1">Express</p>
              <p className="text-gray-800 py-1">JavaScripts</p>
              <p className="text-gray-800 py-1">TypeScript</p>
              <p className="text-gray-800 py-1">Git</p>
              <p className="text-gray-800 py-1">GitHub</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} alt="thumbnail icon"/>
              <h3 className="text-lg font-medium pt-8 pb-2 ">Consulting</h3>
              <p className="py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="font-burtons text-3xl py-1 dark:text-white ">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I&apos;ve done remote work for
              <span className="text-teal-500"> Agencies </span>
              consulted for <span className="text-teal-500">Startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <span className="basis-1/3 flex-1 ">
              <Button href="https://github.com/bocacode/bocacode-intranet-typescript">
                <Image
                alt="a group of boca code students"
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  // layout="responsive"
                  src={bocacode}
                />{" "}
              </Button>
            </span>
            <div className="basis-1/3 flex-1">
              <Button href="https://github.com/beboopr/pitch-vote">
                <Image
                alt="pitch voting app made from Boca Code students"
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  // layout="responsive"
                  src={pitchvote}
                />{" "}
              </Button>
            </div>
            <div className="basis-1/3 flex-1">
              <Button href="https://github.com/beboopr/react-movies">
                <Image
                alt="a project created for movies with a horror theme"
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  // layout="responsive"
                  src={reactmovies}
                />{" "}
              </Button>
            </div>
            <div className="basis-1/3 flex-1">
              <Button href="https://github.com/beboopr/united-front">
                <Image
                alt="a full CRUD web app"
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  // layout="responsive"
                  src={united}
                />{" "}
              </Button>
            </div>
            {/* <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div> */}
          </div>
        </section>
      </main>
    </div>
  );
}
